# Generated by Django 3.1.3 on 2024-11-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='voluntary_point',
            field=models.IntegerField(default=0),
        ),
    ]
