# Generated by Django 3.1.3 on 2024-11-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20241119_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authorization',
            field=models.IntegerField(default=0),
        ),
    ]
