# Generated by Django 3.1.3 on 2024-11-24 20:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20241123_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_list',
            name='buy_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 24, 20, 51, 16, 700118, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uploaded_product',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 24, 20, 51, 16, 699121, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uploaded_product',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 24, 20, 51, 16, 699121, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1),
        ),
    ]
