# Generated by Django 3.1.3 on 2024-11-27 21:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20241125_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_list',
            name='buy_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 27, 21, 58, 46, 950251, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uploaded_product',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 27, 21, 58, 46, 949256, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uploaded_product',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 27, 21, 58, 46, 949256, tzinfo=utc)),
        ),
    ]
