# Generated by Django 3.1.3 on 2024-11-30 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20241130_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_list',
            name='pay_method',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buy_list',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.uploaded_product'),
        ),
    ]
