# Generated by Django 3.1.3 on 2024-12-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20241201_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodExamples',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_image', models.ImageField(null=True, upload_to='good_example_images/')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=2000)),
            ],
        ),
    ]
